// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Test2.Models;

namespace Test2.Models
{
    public partial interface IJobContextProcedures
    {
        Task<int> NEWSIDAsync(string tableName, OutputParameter<string> returnSID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_ACPD_CreateResult>> usp_ACPD_CreateAsync(string inBox_Json, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_AddLogAsync(byte? _InBox_ReadID, string _InBox_SPNAME, Guid? _InBox_GroupID, string _InBox_ExProgram, string _InBox_ActionJSON, OutputParameter<string> _OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
